version: '3'

services:
  db:
    restart: always
    container_name: 'postgres'
    image: 'postgres:9.6.5'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    volumes:
      - 'ft_pgdata:/var/lib/postgresql/data/'
      - 'ft_pglog:/var/log/postgresql'
      - 'ft_pgetc:/etc/postgresql'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - db

volumes:
  ft_pgdata:
  ft_pglog:
  ft_pgetc: